export const DANANG_ADMINISTRATIVE_UNITS = [
  "Phường Hải Châu",
  "Phường Hòa Cường",
  "Phường Thanh Khê",
  "Phường An Khê",
  "Phường An Hải",
  "Phường Sơn Trà",
  "Phường Ngũ Hành Sơn",
  "Phường Hòa Khánh",
  "Phường Hải Vân",
  "Phường Liên Chiểu",
  "Phường Cẩm Lệ",
  "Phường Hòa Xuân",
  "Phường Tam Kỳ",
  "Phường Quảng Phú",
  "Phường Hương Trà",
  "Phường Bàn Thạch",
  "Phường Điện Bàn",
  "Phường Điện Bàn Đông",
  "Phường An Thắng",
  "Phường Điện Bàn Bắc",
  "Phường Hội An",
  "Phường Hội An Đông",
  "Phường Hội An Tây",
  "Xã Hòa Vang",
  "Xã Hòa Tiến",
  "Xã Bà Nà",
  "Xã Núi Thành",
  "Xã Tam Mỹ",
  "Xã Tam Anh",
  "Xã Đức Phú",
  "Xã Tam Xuân",
  "Xã Tây Hồ",
  "Xã Chiên Đàn",
  "Xã Phú Ninh",
  "Xã Lãnh Ngọc",
  "Xã Tiên Phước",
  "Xã Thạnh Bình",
  "Xã Sơn Cẩm Hà",
  "Xã Trà Liên",
  "Xã Trà Giáp",
  "Xã Trà Tân",
  "Xã Trà Đốc",
  "Xã Trà My",
  "Xã Nam Trà My",
  "Xã Trà Tập",
  "Xã Trà Vân",
  "Xã Trà Linh",
  "Xã Trà Leng",
  "Xã Thăng Bình",
  "Xã Thăng An",
  "Xã Thăng Trường",
  "Xã Thăng Điền",
  "Xã Thăng Phú",
  "Xã Đồng Dương",
  "Xã Quế Sơn Trung",
  "Xã Quế Sơn",
  "Xã Xuân Phú",
  "Xã Nông Sơn",
  "Xã Quế Phước",
  "Xã Duy Nghĩa",
  "Xã Nam Phước",
  "Xã Duy Xuyên",
  "Xã Thu Bồn",
  "Xã Điện Bàn Tây",
  "Xã Gò Nổi",
  "Xã Đại Lộc",
  "Xã Hà Nha",
  "Xã Thượng Đức",
  "Xã Vu Gia",
  "Xã Phú Thuận",
  "Xã Thạnh Mỹ",
  "Xã Bến Giằng",
  "Xã Nam Giang",
  "Xã Đắc Pring",
  "Xã La Dêê",
  "Xã La Êê",
  "Xã Sông Vàng",
  "Xã Sông Kôn",
  "Xã Đông Giang",
  "Xã Bến Hiên",
  "Xã Avương",
  "Xã Tây Giang",
  "Xã Hùng Sơn",
  "Xã Hiệp Đức",
  "Xã Việt An",
  "Xã Phước Trà",
  "Xã Khâm Đức",
  "Xã Phước Năng",
  "Xã Phước Chánh",
  "Xã Phước Thành",
  "Xã Phước Hiệp",
  "Đặc khu Hoàng Sa",
  "Xã Tam Hải",
  "Xã Tân Hiệp",
] as const;
