server:
  port: 8082
  tomcat:
    max-http-form-post-size: 10000000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WebApartment?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: ducthang30082004@gmail.com
    password: nxxj lejr iova juux
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jmx:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org:
      springframework:
        beans:
          factory=DEBUG:

api:
  prefix: /api/v1

jwt:
  expiration: 604800 #7 days = 60 * 60 * 24 * 7
  secretKey: 2NWHQt4BeUzp4bo3PJyZkK39tU9HLckNPBCDMz30zZ4=

cloudinary:
  cloud-name: de7vukn0u
  api-key: 749648341948272
  api-secret: McRmuwPpfPZg6Y93H98kWKcdIjw

vnpay:
  tmn-code: WBRTA2N0
  hash-secret: ZV3QXXE6ZY38LE2F6GDGHFHUFCPZWV2D
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8082/api/v1/thanh-toan/vnpay-return

sepay:
  api-key: webapartment_sepay_2026
  bank-code: TPBank
  bank-account: 00002784934
  account-name: NGUYEN DUC THANG