server:
  port: 8082
  tomcat:
    max-http-form-post-size: 10000000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WebApartment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: wyky91334@gmail.com
    password: jtbl fsei qazd krbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jmx:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org:
      springframework:
        beans:
          factory=DEBUG:

api:
  prefix: /api/v1

jwt:
  expiration: 604800 #7 days = 60 * 60 * 24 * 7
  secretKey: 2NWHQt4BeUzp4bo3PJyZkK39tU9HLckNPBCDMz30zZ4=
  resetExpiration: 900

app:
  frontend-reset-password-url: http://localhost:5173/reset-password

cloudinary:
  cloud-name: de7vukn0u
  api-key: 749648341948272
  api-secret: McRmuwPpfPZg6Y93H98kWKcdIjw